version: '3'
services:
  db:
    image: oleksiygontarpersonal/confin:db-0.0.0
    build: .
    container_name: db.confin
    environment:
      POSTGRES_PASSWORD: super_secret_admin
      APP_USER_PASSWORD: app_secret
    ports:
    - 5432:5432

  cache:
    image: redis:6.2.1-alpine
    container_name: cache.confin
    ports:
      - 6379:6379

networks:
  default:
    external:
      name: confin
