name: "Frontend CI"
on:
  push:
    paths:
      - "frontend/**/*"
      - ".github/workflows/frontend.yml"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('./frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
        working-directory: ./frontend

      - run: npm run build
        working-directory: ./frontend

      - name: Login to Registry
        uses: docker/login-action@v2
        if: github.ref_name == 'main'
        with:
          username: oleksiygontarpersonal
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: docker-compose build
        if: github.ref_name == 'main'
        working-directory: ./frontend

      - name: Push image
        run: docker-compose push
        if: github.ref_name == 'main'
        working-directory: ./frontend

      - name: Configure SSH
        if: github.ref_name == 'main'
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/tickets-server.pem
          chmod 600 ~/.ssh/tickets-server.pem
          cat >>~/.ssh/config <<END
          Host tickets-server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/tickets-server.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ec2-user
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ec2-18-197-54-213.eu-central-1.compute.amazonaws.com

      - name: Pull image on server
        if: github.ref_name == 'main'
        run: ssh tickets-server 'docker pull oleksiygontarpersonal/confin:frontend-0.0.0'

      - name: Apply change on server
        if: github.ref_name == 'main'
        run: ssh tickets-server 'cd ~/confin && docker-compose up -d frontend'
